version: '3.8'

services:
  # Golang application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store-management
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@host.docker.internal:5432/store-management"
      JWT_SECRET: "secret"
      JWT_DURATION: "1h"
    ports:
      - "8080:8080"

  # Postgres database
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "store-management"
    volumes:
      - ./migrations/migrate.sql:/docker-entrypoint-initdb.d/init.sql
